# docker-compose.yml

version: "3.9"
services:
  load_balancer:
    build: ./load_balancer
    restart: on-failure
    ports:
      - 80:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  metric_collector:
    build: ./metric_collector
    restart: on-failure
    ports:
      - 9090:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ###########################
  # This section is just for testing purposes. You can run your applications manually.
  application:
    build: ./application
    restart: on-failure
    ports:
      - 8000:8000
  ###########################
